### ISSUE TITLE
Error putting S3 CORS: MalformedXML

### ISSUE THREAD

**Issue by sdanieru** [realglobe-Inc/terraform-aws-static-website#10]
Hi, when attempting to run `terraform apply` with the module (v2.3.0), it quits with the following error:

```
Error: Error putting S3 CORS: MalformedXML: The XML you provided was not well-formed or did not validate against our published schema
	status code: 400, request id: <request_id>, host id: <host_id>
```

Please let me know if there's any other information I  can provide to help  troubleshoot this.

**Comment by s-oku** [comment]
Hi @sdanieru , thank you for reporting.

This issue is same with this.
https://github.com/realglobe-Inc/terraform-aws-static-website/issues/6

Please try to pass your domain like this

```
module "website" {
  source = "realglobe-Inc/static-website/aws"
  version = "2.3.0"
  ...
  # append this line, and only an origin is allowed.
  cors_allowed_origins = list("https://your.domain.com")
```

or this PR will fix the bug.
https://github.com/realglobe-Inc/terraform-aws-static-website/pull/11

Thank you!
