### ISSUE TITLE
index.html

### ISSUE THREAD

**Issue by kaihendry** [realglobe-Inc/terraform-aws-static-website#5]
How do I make https://talks.webconverger.com/2019-01-17/ URLs work? i.e. it defaults to index.html ? Thanks!

**Comment by FujiHaruka** [comment]
@s-oku

**Comment by s-oku** [comment]
Upload files on S3 bucket, and CloudFront serves S3 objects.

- https://your-domain.com/favicon.ico -> `s3://your-bucket/favicon.ico`
- https://your-domain.com/assets/style.css -> `s3://your-bucket/assets/style.css`
- https://your-domain.com/2019-01-17/index.html -> `s3://your-bucket/2019-01-17/index.html`

If file does not exist on S3 or URL ends with `/`, CloudFront serves `index.html` (Default Root Object).

- https://your-domain.com/not-exist.html -> `s3://your-bucket/not-exist.html` (file does not exist) -> `s3://your-bucket/index.html`
- https://your-domain.com/2019-01-17/ -> `s3://your-bucket/index.html` (ends with `/`)

And if you set CloudFront Origin Path, it appends prefix to S3 object path.

- https://your-domain.com/index.html -> `s3://your-bucket/dev/index.html`.

**Comment by kaihendry** [comment]
I see that https://talks.webconverger.com/ -> s3://talks.webconverger.com/index.html works

but why can't I expect https://talks.webconverger.com/2019-07-16/ -> s3://talks.webconverger.com/2019-07-16/index.html ?

I guess I need to look for another terraform module that sets up **Static website hosting** on S3 and uses that as it's origin? Since I don't think this one does it like that. Or am I mistaken?

**Comment by s-oku** [comment]
Unfortunately CloudFront doesn't support DirectoryIndex. So you need to use Lambda@Edge.
https://aws.amazon.com/jp/blogs/compute/implementing-default-directory-indexes-in-amazon-s3-backed-amazon-cloudfront-origins-using-lambdaedge/

This repository may help you.
https://github.com/realglobe-Inc/terraform-aws-lambda-edge-basic-auth

Download and overwrite `archive_file.tf`, and set lambda_function_associations.

```
lambda_function_associations = { "origin-request": module.lambda_edge.lambda_qualified_arn }
```

**Comment by kaihendry** [comment]
But [S3 Website](https://www.terraform.io/docs/providers/aws/r/s3_bucket.html) does support it. So if your S3 configuration used **website** you could use it, like so:

<img src="https://s.natalian.org/2019-07-17/1563357116_2560x1440.png">

**Comment by s-oku** [comment]
Yes, S3 supports. But if so, you can access http://natalian.s3-website-ap-southeast-1.amazonaws.com directly.
This module is implemented to let you host website **only your custom domain and HTTPS**, so S3 website is disabled.

**Comment by kaihendry** [comment]
Oh I thought it would be S3 Website + Cloudfront. I guess I need `terraform destroy` and find another module.

Thanks for helping nonetheless.
