### ISSUE TITLE
CORS Support

### ISSUE THREAD

**Issue by FujiHaruka** [realglobe-Inc/terraform-aws-static-website#6]
https://aws.amazon.com/jp/premiumsupport/knowledge-center/no-access-control-allow-origin-error/

**Comment by FujiHaruka** [comment]
#7 resolves

**Comment by heri16** [comment]
@FujiHaruka  if cors_allowed_origin is set to default, this error is produced:

```
Error: Error putting S3 CORS: MalformedXML: The XML you provided was not well-formed or did not validate against our published schema
	status code: 400,
```

How can we disable CORS?

**Comment by heri16** [comment]
https://github.com/hashicorp/terraform-provider-aws/issues/9334#issuecomment-685396596
